### ISSUE TITLE
rend: Test failed on s390x and armv7hl arch

### ISSUE THREAD

**Issue by ghost** [rkyv/rend#2]
Hi. Test failed on fedora koji. Latest version 0.3.1. The issue is the same on the two arch.
https://kojipkgs.fedoraproject.org//work/tasks/592/73360592/build.log
https://kojipkgs.fedoraproject.org//work/tasks/597/73360597/build.log

error[E0433]: failed to resolve: use of undeclared type `AtomicU16_be`
   --> src/lib.rs:470:46
    |
470 |                 mem::transmute::<_, [u8; 2]>(AtomicU16_be::new(0x0102))
    |                                              ^^^^^^^^^^^^ use of undeclared type `AtomicU16_be`
error[E0433]: failed to resolve: use of undeclared type `AtomicU16_le`
   --> src/lib.rs:474:46
    |
474 |                 mem::transmute::<_, [u8; 2]>(AtomicU16_le::new(0x0102))
    |                                              ^^^^^^^^^^^^ use of undeclared type `AtomicU16_le`
error[E0433]: failed to resolve: use of undeclared type `AtomicU32_be`
   --> src/lib.rs:480:46
    |
480 |                 mem::transmute::<_, [u8; 4]>(AtomicU32_be::new(0x01020304))
    |                                              ^^^^^^^^^^^^ use of undeclared type `AtomicU32_be`
error[E0433]: failed to resolve: use of undeclared type `AtomicU32_le`
   --> src/lib.rs:484:46
    |
484 |                 mem::transmute::<_, [u8; 4]>(AtomicU32_le::new(0x01020304))
    |                                              ^^^^^^^^^^^^ use of undeclared type `AtomicU32_le`
error[E0433]: failed to resolve: use of undeclared type `AtomicU64_be`
   --> src/lib.rs:490:46
    |
490 |                 mem::transmute::<_, [u8; 8]>(AtomicU64_be::new(0x0102030405060708))
    |                                              ^^^^^^^^^^^^ use of undeclared type `AtomicU64_be`
error[E0433]: failed to resolve: use of undeclared type `AtomicU64_le`
   --> src/lib.rs:494:46
    |
494 |                 mem::transmute::<_, [u8; 8]>(AtomicU64_le::new(0x0102030405060708))
    |                                              ^^^^^^^^^^^^ use of undeclared type `AtomicU64_le`
error: aborting due to 6 previous errors

**Comment by djkoloski** [comment]
More test problems. It looks like `rend` is not providing atomic support, which is correct for the arch since it's not in the whitelist. However, the tests are not accounting for this and attempting to use atomic types anyway. Fix is on the way.

**Comment by djkoloski** [comment]
Should be fixed by 073954bb062f3eb15f9afc04f739b670e6de0838 and released in 0.3.2

**Comment by ghost** [comment]
Test work now. Thanks!
